SELECT 
    MINISTRY.MINISTRYNAME, 
    MINISTRY.MINISTERFNAME,
    MINISTRY.MINISTERLNAME, 
    MINISTRY.PROVINCE,
    (SELECT COUNT(*) FROM FACILITY WHERE FACILITY.MINISTRYID = MINISTRY.MINISTRYID) AS NumFacilities,
    (SELECT COUNT(DISTINCT EMPLOYEEID) FROM EMPLOYEEREGISTRATION WHERE EMPLOYEEREGISTRATION.FACILITYID IN (SELECT FACILITYID FROM FACILITY WHERE FACILITY.MINISTRYID = MINISTRY.MINISTRYID) AND ENDDATE IS NULL) AS NumEmployees,
    (SELECT COUNT(DISTINCT STUDENTID) FROM STUDENTREGISTRATION WHERE STUDENTREGISTRATION.FACILITYID IN (SELECT FACILITYID FROM FACILITY WHERE FACILITY.MINISTRYID = MINISTRY.MINISTRYID) AND ENDDATE IS NULL) AS NumStudents
FROM MINISTRY
ORDER BY NumFacilities DESC;
